name: need changeset

on:
  pull_request:
    paths:
      - "src/**"

jobs:
  changeset-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.6.0
        with:
          node-version-file: .tool-versions
      - name: Test | Run changeset status
        if: github.actor != 'renovate[bot]'
        run: pnpm changeset status --since origin/main
