name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.5.0
        with:
          node-version-file: .tool-versions
      - name: Setup | turborepo cache
        uses: re-taro/actions/turbo-cache@v3.5.0
      - name: Test | Build
        run: pnpm build
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.5.0
        with:
          node-version-file: .tool-versions
      - name: Setup | turborepo cache
        uses: re-taro/actions/turbo-cache@v3.5.0
      - name: Setup | Build
        run: pnpm build
      - name: Test | Lint
        run: pnpm lint
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.5.0
        with:
          node-version-file: .tool-versions
      - name: Setup | turborepo cache
        uses: re-taro/actions/turbo-cache@v3.5.0
      - name: Setup | Build
        run: pnpm build
      - name: Test | Unit
        run: pnpm test
  changeset-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.5.0
        with:
          node-version-file: .tool-versions
      - name: Test | Run changeset status
        run: pnpm changeset status --since origin/main
