name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.6.0
        with:
          node-version-file: .tool-versions
      - name: Test | Build
        run: pnpm build
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.6.0
        with:
          node-version-file: .tool-versions
      - name: Setup | Build
        run: pnpm build
      - name: Test | Lint
        run: pnpm lint
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.6.0
        with:
          node-version-file: .tool-versions
      - name: Test | Unit
        run: pnpm test
