name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.3.2
        with:
          node-version-file: .tool-versions
      - name: Test | Build
        run: pnpm build
      - name: Test | Lint
        run: pnpm lint
      - name: Test | Type Check
        run: pnpm typecheck
      - name: Test | Test
        run: pnpm test
