name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install
        run: pnpm install --no-frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Lint
        run: pnpm run lint
