name: manual-deploy-production
run-name: Deploy Production from ${{ inputs.ref }}

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to deploy (e.g. main, v1.0.0, c91ee3c, etc.)"
        required: true

jobs:
  manual-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - name: npm
            url: https://registry.npmjs.org/
          - name: GitHub Packages
            url: https://npm.pkg.github.com/
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ inputs.ref }}
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.3.2
        with:
          node-version-file: .tool-versions
      - name: Setup | Registry
        uses: actions/setup-node@v3.8.2
        with:
          scope: "@re-taro"
          registry-url: ${{ matrix.url }}
      - name: Publish | Build
        run: pnpm build
      - name: Publish | ${{ matrix.name }}
        run: pnpm publish -r --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ matrix.name == 'npm' && secrets.NPM_TOKEN || secrets.GITHUB_TOKEN }}
